version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Cambia esto por una contrase침a m치s segura
      MYSQL_DATABASE: series_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword  # Cambia esto por una contrase침a m치s segura
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: ../backend
    container_name: go-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: series_tracker
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
